//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMU_PlatformTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMU_PlatformTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Bias_Updating : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Bias_Updating_Str {
            get {
                return ResourceManager.GetString("Bias_Updating_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COM Searching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ComSearch_Str {
            get {
                return ResourceManager.GetString("ComSearch_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Connecting_Str {
            get {
                return ResourceManager.GetString("Connecting_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Disconnected_Str {
            get {
                return ResourceManager.GetString("Disconnected_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnecting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Disconnecting_Str {
            get {
                return ResourceManager.GetString("Disconnecting_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_Str {
            get {
                return ResourceManager.GetString("Error_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected mode is not compatible with the app.
        ///Please select another mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Format_Err_Str {
            get {
                return ResourceManager.GetString("Format_Err_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Does not work with older firmware.
        ///Please update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Old_firm_Str {
            get {
                return ResourceManager.GetString("Old_firm_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Question に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Question_Str {
            get {
                return ResourceManager.GetString("Question_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ready_Str {
            get {
                return ResourceManager.GetString("Ready_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Running_Str {
            get {
                return ResourceManager.GetString("Running_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sec_Str {
            get {
                return ResourceManager.GetString("Sec_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor not found.
        ///Check connection or check sensor model number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sens_Inco_Str {
            get {
                return ResourceManager.GetString("Sens_Inco_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the settings? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Que_Str {
            get {
                return ResourceManager.GetString("Setting_Que_Str", resourceCulture);
            }
        }
    }
}
